services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    restart: always
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_data:/var/www/html
  
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    restart: always
    networks:
      - inception_network
  
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    restart: always
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
  
  static_site:
    build: ./requirements/bonus/static_site
    container_name: static_site
    image: static_site
    ports:
      - "8080:8080"
    restart: always
    networks:
      - inception_network
  
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - inception_network
    depends_on:
      - mariadb
    ports:
      - "8081:8081"
  
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer
    ports:
      - "9000:9000"
    restart: always
    networks:
      - inception_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  inception_network:
    name: inception_network

volumes:
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/username/data/wordpress
      o: bind
  
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      type: none
      device: /home/username/data/mariadb
      o: bind
  
  portainer_data:
    driver: local
    name: portainer_data
    driver_opts:
      type: none
      device: /home/username/data/portainer
      o: bind
